# Generated by Django 3.2.4 on 2021-07-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name', 'second_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование книги')),
                ('image', models.ImageField(upload_to='book_images')),
                ('short_desc', models.CharField(max_length=255, verbose_name='Краткое описание продукта')),
                ('description', models.TextField(verbose_name='Полное описание продукта')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='цена продукта')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество на складе')),
                ('age_restrictions', models.CharField(max_length=10, verbose_name='Возрастной рейтинг')),
                ('edition_language', models.CharField(max_length=50, verbose_name='Язык издания')),
                ('year_of_issue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('edition_type', models.CharField(blank=True, max_length=255, verbose_name='Тип издания')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Название на оригинале')),
                ('ISBN', models.CharField(blank=True, max_length=255, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Переводчик',
                'verbose_name_plural': 'Переводчики',
                'ordering': ['name', 'second_name'],
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес в упаковке, г')),
                ('cover_type', models.CharField(blank=True, choices=[('soft', 'Мягкая обложка'), ('hard', 'Твердая обложка')], max_length=40, verbose_name='Тип обложки')),
                ('edition_format', models.CharField(blank=True, max_length=50, verbose_name='Формат издания')),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('book_type', models.CharField(choices=[('Digital', 'Цифровая книга'), ('Printed', 'Печатная книга')], max_length=20, verbose_name='Тип издания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Технические характеристики книги',
                'verbose_name_plural': 'Технические характеристики книг',
                'ordering': ['book_type'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.publisher', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.translator', verbose_name='Переводчик'),
        ),
    ]
