# Generated by Django 3.2.5 on 2021-07-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='for_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book', unique=True, verbose_name='Книга'),
        ),
    ]
