# Generated by Django 3.2.4 on 2021-07-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='age',
        ),
    ]
