# Generated by Django 3.2.5 on 2021-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_alter_shopuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
